apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-kubernetes
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: hello-kubernetes
    origin: hello-kubernetes
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: hello-kubernetes
      origin: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
        origin: hello-kubernetes
    spec:
      serviceAccountName: hello-kubernetes
      containers:
        - name: hello-kubernetes
          image: "paulbouwer/hello-kubernetes:1.10"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
          - name: PORT
            value: "8080"
          - name: MESSAGE
            value: "Hello, World"
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: CONTAINER_IMAGE
            value: "paulbouwer/hello-kubernetes:1.10"
  strategy:
    blueGreen:
      activeService: hello-kubernetes
      previewService: hello-kubernetes-preview-service
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 20
