---
# Source: hello-kubernetes/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: hello-kubernetes
    origin: hello-kubernetes
---
# Source: hello-kubernetes/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-preview-service
  namespace: default
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: hello-kubernetes
    origin: hello-kubernetes
